//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPLIDAR_Mapping {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.12.0.0")]
    internal sealed partial class TileRegulatorSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static TileRegulatorSettings defaultInstance = ((TileRegulatorSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new TileRegulatorSettings())));
        
        public static TileRegulatorSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int BaseTileTrustIncrement {
            get {
                return ((int)(this["BaseTileTrustIncrement"]));
            }
            set {
                this["BaseTileTrustIncrement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public float MaxTileTrustIncrement {
            get {
                return ((float)(this["MaxTileTrustIncrement"]));
            }
            set {
                this["MaxTileTrustIncrement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int BaseTileTrustDecrement {
            get {
                return ((int)(this["BaseTileTrustDecrement"]));
            }
            set {
                this["BaseTileTrustDecrement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public float MaxTileTrustDecrement {
            get {
                return ((float)(this["MaxTileTrustDecrement"]));
            }
            set {
                this["MaxTileTrustDecrement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int BaseTileDecayRate {
            get {
                return ((int)(this["BaseTileDecayRate"]));
            }
            set {
                this["BaseTileDecayRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int MaxTileDecayRate {
            get {
                return ((int)(this["MaxTileDecayRate"]));
            }
            set {
                this["MaxTileDecayRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int BaseTileTrustThreshold {
            get {
                return ((int)(this["BaseTileTrustThreshold"]));
            }
            set {
                this["BaseTileTrustThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MinTileTrustThreshold {
            get {
                return ((int)(this["MinTileTrustThreshold"]));
            }
            set {
                this["MinTileTrustThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int MaxTileTrustThreshold {
            get {
                return ((int)(this["MaxTileTrustThreshold"]));
            }
            set {
                this["MaxTileTrustThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RegulatorEnabled {
            get {
                return ((bool)(this["RegulatorEnabled"]));
            }
            set {
                this["RegulatorEnabled"] = value;
            }
        }
    }
}
